# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NTQyNzE2OTgxMzkzYjFmYTA0MGE3YThhMjAwMmU3MzQ3NzIwODIwNzVkMTRkODMyYjlhMzhlYTJjNjc5NmZjNDQzYzlhNDA4ODJkZDQzYzRhNGIyODczMjI0Yzk2MzEyNWEyOWZlZTUyZDU2MDU0OWVlZmI2NTBjODQ3NzEwZDY=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
